### ISSUE TITLE
[android] 微信登录，没有唤起微信，直接返回ERR_AUTH_DENIED

### ISSUE THREAD

**Issue by aqingsao** [vilic/cordova-plugin-wechat#10]
@vilic 您好，

该插件的使用过程中，严格按照说明步骤，签名、appId均设置正常。Wechat.isInstalled方法调用也正常，但是微信登录接口（Wechat.auth）很多时候无法唤起微信进行授权：
  var scope = "snsapi_userinfo";
  Wechat.auth(scope, function (response) {
    // 没有进入这里
  }, function (error) {
    // 返回的error是 'ERR_AUTH_DENIED'
  });
通过5部android手机测试，发现结果如下：
1. 如果微信没有登录，则会唤起微信，登录后，直接返回到应用，并报'ERR_AUTH_DENIED'错误
2. 如果微信已经登录，第一次使用时，有2部手机能够唤起微信，让用户授权；有3部手机无法唤起微信，直接返回'ERR_AUTH_DENIED'错误；
3. 如果微信已经登录，第二次及更多地使用，均不会唤起微信，直接返回'ERR_AUTH_DENIED'错误；

不知道您有没有遇到类似的问题？谢谢！

张晓庆

**Comment by vilic** [comment]
囧，抱歉这部分功能在我的插件里其实，，，是没有的。

Sent from my Lumia 930
________________________________

**Comment by aqingsao** [comment]
@vilic 
谢谢您的回复。 请问有没有计划什么时候实现？

**Comment by vilic** [comment]
抱歉因为自己暂时没有这个需求, 所以可能短时间内不会加. 不过欢迎 PR.

**Comment by kinhunt** [comment]
@vilic: 求加
