### ISSUE TITLE
Wechat is not defined

### ISSUE THREAD

**Issue by ayonge20** [vilic/cordova-plugin-wechat#11]
请问，这个问题需要解决么？

**Comment by vilic** [comment]
你好, 请确认在 deviceready 后调用~

**Comment by ayonge20** [comment]
我看到的例子中 ，没有引入 Wechat的 ，也就是说这个只能在device上才可以使用，浏览器中不行吧

**Comment by vilic** [comment]
嗯~

**Comment by ayonge20** [comment]
请问一下，在模拟器上跑，然后进行微信授权，发现Wechat还是没有定义，请问这个该怎么决解，不过在模拟器上跑的APK是未签名的。另外，我能加你QQ么，请教好方便点？

**Comment by vilic** [comment]
不是很方便加 QQ 不好意思. 可能是 plugin 安装不正确, 试试重新安装并确认没有报错.

**Comment by ayonge20** [comment]
删除Wechat插件之后，再次安装，在模拟器上运行还是出现 Wechat 未定义的错误

**Comment by vilic** [comment]
能贴一下代码么囧, 如果还有问题的话.

**Comment by beyond0309** [comment]
你好 有人解决了么？？ 我也遇到了 wechat 找不到的问题。。。

**Comment by vilic** [comment]
这里要注意两个问题, 一个是需要在 cordova 的 deviceready 事件后使用, 另一个是不能通过浏览器模拟.
