### ISSUE TITLE
怎么分享截图图片了？

### ISSUE THREAD

**Issue by qdsang** [vilic/cordova-plugin-wechat#13]
https://github.com/gitawego/cordova-screenshot
找到这个插件， 但是没有找到配合一起使用的方法

**Comment by vilic** [comment]
你好, 可以生成图片的 base64 数据, 再进行分享.

**Comment by qdsang** [comment]
cordova-screenshot 插件支持android 进行base64， ios有办法吗？

**Comment by vilic** [comment]
这个超出插件关注的范围了囧, 请自行解决.
