### ISSUE TITLE
分享链接的时候怎么预设一段文本啊！

### ISSUE THREAD

**Issue by liuzhixiang** [vilic/cordova-plugin-wechat#14]
分享链接的时候，怎么设置默认的分享文字啊？就向分享文本那样。
description没用，设置在description里的内容没有见哪里显示啊！
title是显示在链接图旁边的介绍文字。

**Comment by vilic** [comment]
你好, 文本貌似是不能预设的. Description 里的内容不同设备可能显示不同, 或者根本不显示.
