### ISSUE TITLE
http://registry.cordova.io 似乎被墙了， 把插件放到npm上吧

### ISSUE THREAD

**Issue by BenBBear** [vilic/cordova-plugin-wechat#16]
如题，现在cordova插件基本都是放到npm上了， 比如： https://github.com/apache/cordova-plugin-device/blob/master/package.json

谢谢呢~

**Comment by BenBBear** [comment]
https://github.com/xu-li/cordova-plugin-wechat  明显是更好地选择， 转用这个了

**Comment by vilic** [comment]
囧谢谢提醒, 最近太忙了, 有计划转到 npm 上.

**Comment by vilic** [comment]
我先把这个 issue reopen 一下希望不要介意, 转移到 npm 后我会 close 掉. :D

**Comment by BenBBear** [comment]
喵！ 好的

**Comment by BenBBear** [comment]
不过BTW

我遵循了您的android指南， 可是总是返回ERR_UNKOWN 不知道为什么。。。  但是用了上述另一个Repo的插件后， android分享就成功了 😣

**Comment by vilic** [comment]
囧, 可能是分享的内容问题? 空下来一起看看. 因为在维护的项目比较多, 有的自己暂时没用上的就来不及打理了. 摊手.

**Comment by BenBBear** [comment]
666666  身体最重要不要太累了， 这些都是浮云， 不急

**Comment by vilic** [comment]
:D thx~

**Comment by vilic** [comment]
已经放到 npm 上了, `cordova-plugin-tx-wechat`.
