### ISSUE TITLE
我安装了为什么点击没有反应呢？

### ISSUE THREAD

**Issue by justblv** [vilic/cordova-plugin-wechat#20]
android，应用签名和包名都保持和微信开放平台申请的一致，可是点击为什么没有丝毫反应，也没有报错。

**Comment by ace68723** [comment]
没有反应＋1也没抱错

**Comment by vilic** [comment]
话说先确认下 #21 这个问题. 调用相关方法前请确认 deviceready 事件已触发.

**Comment by justblv** [comment]
问题已经解决了，谢谢。还是签名的问题，粗心大意了。之前虽然通过工具查看apk的签名和微信开放平台提交的签名是一样的，但这还不够！解决办法就是把代码中“多处”有签名字符串的地方都改掉，问题就解决了。

**Comment by vilic** [comment]
@justblv :+1:  话说顺便问下, 你在编译的过程中是否也遇到过 #21 这个问题? 有劳呀~

**Comment by justblv** [comment]
没遇到过

**Comment by vilic** [comment]
@justblv 喔, 谢谢~
