### ISSUE TITLE
分享网页到朋友圈，缩略图不能显示

### ISSUE THREAD

**Issue by guosky99** [vilic/cordova-plugin-wechat#22]
WeChat.share({
                type: WeChat.ShareType.webpage,
                title: ' 这是标题',
                thumbData:'这是我图片的base64编码字符串，前面加不加data:image/png;base64,都不行 ',
                url: 'http://www.xxxxxx.com'
            }, shareType, function () {
                //分享成功
            }, function (reason) {
                // 分享失败
            });

**Comment by guosky99** [comment]
请大神指点

**Comment by vilic** [comment]
不能显示具体是指? 没有缩略图还是缩略图是坏的?

**Comment by guosky99** [comment]
谢谢vilic的回复，缩略图应该是坏的，如果不填写thumbData字段，还能显示一个默认的图片（有个连接图标的图片），如果将thumbData字段赋值一个图片的base64字符，就什么都不显示了。

**Comment by guosky99** [comment]
缩略图显示出来了，谢谢vilic

**Comment by vilic** [comment]
:D 棒~
