### ISSUE TITLE
两个问题要请教一下

### ISSUE THREAD

**Issue by huawin03** [vilic/cordova-plugin-wechat#24]
第一个  ： 配置这块，应该不是 config.xml 文件吧，应该是 AndroidManifest.xml吧
第二个 ： ant.properties 这个里面的路径治怎么配置？求个大概的demo看一下，我配置的cordova run android --release 后一直是unsign的包 ，我是这样写的，key.store=C:\Users\guoqq\Desktop\demo\weixinticket.keystore，应该是没取到里面的东西。然后我用eclipse 下 Android-tools输出包是带sign的

**Comment by vilic** [comment]
一. 这样的 cordova 的 config.xml 里可以加入相关文件的配置, 推荐在可能的情况下还是写到这里, 让 cordova 帮你生成对应的项目及其文件.
二. 中间有没有报错或警告信息?

**Comment by huawin03** [comment]
##命令是 cordova run android --release 
##显示的是 
BUILD SUCCESSFUL

Total time: 2 mins 27.087 secs
Built the following apk(s):
    D:\Program Files (x86)\Zend\Apache2\htdocs\h5-app\apk\platforms\android\buil
d\outputs\apk\android-release-unsigned.apk
Using apk: D:\Program Files (x86)\Zend\Apache2\htdocs\h5-app\apk\platforms\andro
id\build\outputs\apk\android-release-unsigned.apk
可以看出两个都是未签名的，打出的包都是未签名的，是不是我的路径写错了？？能给个正确路径的demo或者代码吗？？

##我把错误贴出来 
ERROR: Failed to launch application on device: ERROR: Failed to install apk to d
evice:  pkg: /data/local/tmp/android-release-unsigned.apk
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]

ERROR running one or more of the platforms: Error: cmd: Command failed with exit
 code 1
You may not have the required environment or OS to run this project

**Comment by vilic** [comment]
嗯按报错提示可能是没找到证书. 确认下之前的步骤都正确, 然后尝试使用相对路径看看?

**Comment by huawin03** [comment]
相对路径也不行，我放到同级目录下
key.store=weixinticket.keystore
key.alias=h5_yuntoo
key.store.password=abcde54321
key.alias.password=abcde54321
还是找不到

**Comment by vilic** [comment]
`ant.properties` 文件是放在 `platforms/android/` 目录下的吗?

**Comment by huawin03** [comment]
两个文件（ant.properties 和 weixinticket.keystore）都在这，D:\Program Files (x86)\Zend\Apache2\htdocs\h5-app\apk\platforms\android，是不是打包的时候，cordova没有去执行ant.properties 这个文件？？

**Comment by huawin03** [comment]
apk是用来放cordova和打包用的，h5-app还有个src目录
至于你说的项目目录，我没太明白，囧。。。。

**Comment by vilic** [comment]
囧, 那应该不会有错呀.  我看了下 stackoverflow 上有个 windows 下的例子, 路径用的 C:\\ 双反斜杠, 试试看?

**Comment by huawin03** [comment]
相对路径成功了，不过我用的是eclipse打包的。谢谢作者了，辛苦作者了。

**Comment by vilic** [comment]
囧, 没~
