### ISSUE TITLE
插件在Android平台顺利完成，但是调用分享函数没效果

### ISSUE THREAD

**Issue by shanelisy** [vilic/cordova-plugin-wechat#3]
你好！以下是测试调用代码，程序不报任何错误，但是就是没有分享出去，所使用AppID已经在微信开发者平台获取'分享到朋友圈'和'发送给朋友'的权限,最为奇怪的是console也看不到任何成功或者失败的日志，调用函数没有任何效果，这是怎么回事？
onDeviceReady: function() {
        app.receivedEvent('deviceready');
		WeChat.share('李克强：让农民工生活有希望', WeChat.Scene.session, function () {
			console.log('分享成功~');
		}, function (reason) {
			console.log(reason);
		});
		WeChat.share({
			title: '李克强：让农民工生活有希望奋斗有回报',
			description: '据中国政府网4日至6日，国务院总理李克强在广东省委书记胡春华，省长朱小丹陪同下，在深圳、广州考察。',
			url: 'http://world.haiwainet.cn/n/2015/0107/c232591-21605009.html'
		}, WeChat.Scene.timeline, function () {
			console.log('分享成功~');
		}, function (reason) {
			// 分享失败
			console.log(reason);
		});
        console.log('Invoke Finish');
    }
以下是日志：
--------- beginning of /dev/log/system
I/CordovaLog(30158): Changing log level to DEBUG(3)
D/CordovaLog(30158): file:///android_asset/www/index.html: Line 26 : Viewport ta
rget-densitydpi is not supported.
D/CordovaLog(30158): file:///android_asset/www/js/index.js: Line 63 : Received E
vent: deviceready
D/CordovaLog(30158): file:///android_asset/www/js/index.js: Line 52 : Invoke Fin
ish....

**Comment by vilic** [comment]
你好, 一方面建议测试不要用可能被屏蔽的关键字 (虽然这里是问题的概率比较小, 但是以防万一嘛). 另一方面请检查应用签名是否与提交到 Android 平台的签名一致 (这个比较坑, 必须用最终发布用的keystore来签名才能正常调试).

**Comment by shanelisy** [comment]
感谢及时回复，现在情况是我在<project>\platforms\android\res\xml\config.xml和<project>\platforms\android\AndroidManifest.xml都增加了如下内容：
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
另外在微信开发平台的资源下载中下载了签名生成工具，安装到手机，输入我目前Cordova App的package名称获取签名，确认了与开发平台我申请的APPID对应的签名一致，代码也调整成下述情况，还是无法分享，也没有成功/失败的log输出，怎么回事？急死人了！
onDeviceReady: function() {
        app.receivedEvent('deviceready');
		console.log(WeChat+' Share Start...');
		WeChat.share('文本', WeChat.Scene.session, function () {
			console.log('分享成功~');
		}, function (reason) {
			console.log(reason);
		});
		console.log(WeChat+' Share End...');
    },
目前输出日志：
D/CordovaLog(20054): file:///android_asset/www/js/index.js: Line 54 : Received E
vent: deviceready
D/CordovaLog(20054): file:///android_asset/www/js/index.js: Line 37 : [object Ob
ject] Share Start...
D/CordovaLog(20054): file:///android_asset/www/js/index.js: Line 43 : [object Ob
ject] Share End...
我的环境信息：
Cordova 4.1.2
Name: Android 4.4.2
Type: Platform
API level: 19
Revision: 4
微信AppID：wx6fb67cdd9098cff7
应用签名：1bb740dc34d6f9357898407903f817bf
包名：com.mobile.xinxiang

**Comment by vilic** [comment]
别急别急, debug 本身就是漫长而痛苦的. 可以把 cordova 目录打包发送给我一下不 (i#vilic.info)? (另外你的应用通过微信审核了咩?)

**Comment by shanelisy** [comment]
嗯，邮件已发，帮忙抽时间看下。谢谢！

**Comment by vilic** [comment]
https://github.com/vilic/cordova-plugin-wechat/wiki/Android-%E5%BE%AE%E4%BF%A1-SDK-%E7%AD%BE%E5%90%8D%E9%97%AE%E9%A2%98
