### ISSUE TITLE
分享完会黑屏一秒钟左右

### ISSUE THREAD

**Issue by mkliu** [vilic/cordova-plugin-wechat#4]
你有这个问题么？我在小米3上测试的，用的ionic

**Comment by vilic** [comment]
没遇到诶, 我的测试机是 Nexus 4, Android 4.4.

**Comment by mkliu** [comment]
哦，应该是因为分享完了返回的时候刷新了页面导致的。这体验相当不好啊，你的会刷新页面么？

**Comment by vilic** [comment]
按说中间确实是经过了一个 Activity (可以理解为安卓应用的一个页面), 这个是微信的处理逻辑, 但是我这儿确实感觉不明显. 还是说你说的是刷新了网页?

**Comment by mkliu** [comment]
的确刷新了，我本来在angular的一个子页面，后来跳回了主页。所以你的不会跳回主页？

**Comment by vilic** [comment]
咦? 那能接到回调吗? 只是 router 变了还是整个页面都 reload 了?

**Comment by mkliu** [comment]
问题找到了，给你发了个pull request。第一次发pull request，不知道是不是这么弄。
