### ISSUE TITLE
package to.be.replaced.wxapi; 

### ISSUE THREAD

**Issue by jackie19** [vilic/cordova-plugin-wechat#6]
文件WXEntryActivity.java 第一行的 package to.be.replaced.wxapi;  是否是要替换成  config.xml 里的 widget id ？

**Comment by jackie19** [comment]
另外，安卓下分享消息的失败回调： ERR_AUTH_DENIED , 我是按照 https://github.com/vilic/cordova-plugin-wechat/wiki/Android-%E5%BE%AE%E4%BF%A1-SDK-%E7%AD%BE%E5%90%8D%E9%97%AE%E9%A2%98 这份文档一步步操作的， 请有时间的时候帮忙看看，谢谢。

![4 buw_rffjrx noxg277rha](https://cloud.githubusercontent.com/assets/2063608/6552091/90a6daa6-c67c-11e4-9880-46575b768cc7.png)

![uy5dclv4 edfitcu0rwbdbg](https://cloud.githubusercontent.com/assets/2063608/6552092/95b318b6-c67c-11e4-822f-ee4cb57eac61.png)

![csobg0hodv3 mv ruu9n83](https://cloud.githubusercontent.com/assets/2063608/6552096/a137306e-c67c-11e4-8790-4aaa96a66c03.png)

![poaehxr 7nfo 0l9bgevl](https://cloud.githubusercontent.com/assets/2063608/6552103/c91bdf26-c67c-11e4-972b-8a211cefbdfc.png)

**Comment by vilic** [comment]
你好, 替换在安装插件时脚本会自动进行, 所以一般情况下是不需要再手动操作的 (可以检查一下安卓目录下对应目录中的相关文件, 是否替换成了 你的包名.wxapi). 不知道你进入微信界面了吗?

**Comment by jackie19** [comment]
跳转到微信的界面，显示请稍后， 然后就 alert 了 ERR_AUTH_DENIED

**Comment by vilic** [comment]
这个我就不清楚了，应用通过审核了吗？按说进了微信界面说明配置没有问题。

Sent from my Lumia 930
________________________________

**Comment by jackie19** [comment]
![image](https://cloud.githubusercontent.com/assets/2063608/6591482/a5d7688e-c7fb-11e4-9f3f-0fbc54ae2c5f.png)

**Comment by jackie19** [comment]
我刚刚先用其他app分享到微信， 再用我的app，就可以分享了，感觉很奇怪

**Comment by vilic** [comment]
囧, 可能是缓存的问题吧.

**Comment by jackie19** [comment]
总之， 多谢多谢。

**Comment by vilic** [comment]
客气啦~

**Comment by fengfangqian** [comment]
有按照sdk签名通过应用审核，用其他的应用分享后再用我的应用分享也不行

**Comment by vilic** [comment]
囧, 那只能自己折腾看看了, 晚安~
