### ISSUE TITLE
不能分享图片

### ISSUE THREAD

**Issue by cyokvip** [vilic/cordova-plugin-wechat#9]
我设置type是image，然后进入分享界面时候，点击联系人会闪一下，不能分享出去
WeChat
                .share({
                    type: WeChat.ShareType.image,
                    url:'http://xxxtg.png',
                    title: 'aa',
                    description: 'bb'
                }, WeChat.Scene.session, function () {
                    console.log('分享成功~');
                }, function (reason) {
                    // 分享失败
                    console.log(reason);
                });

**Comment by vilic** [comment]
如果进了分享界面, 那一般情况下就不是这边的问题了. 分析 url 不行的话可以尝试 base64.
